name: clima
description: A new Flutter application.

version: 4.0.1+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.3.2+2
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  fluttericon: ^1.0.7
  screenshot: ^0.2.0
  image_gallery_saver: ^1.5.0
  flutter_google_places: ^0.2.6
  uuid: ^2.2.0
  upgrader: ^2.5.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.10
  provider: ^4.3.2+1
  location: ^3.0.2
  location_permissions: ^3.0.0+1
  firebase_messaging: ^7.0.0
  syncfusion_flutter_gauges: ^18.2.57

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Playfair Display
      fonts:
        - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
